import pygame

keydict = {
    pygame.K_SPACE: False, pygame.K_EXCLAIM: False, pygame.K_QUOTEDBL: False, pygame.K_HASH: False,
    pygame.K_DOLLAR: False, pygame.K_PERCENT: False, pygame.K_AMPERSAND: False, pygame.K_QUOTE: False,
    pygame.K_LEFTPAREN: False, pygame.K_RIGHTPAREN: False, pygame.K_ASTERISK: False, pygame.K_PLUS: False,
    pygame.K_COMMA: False, pygame.K_MINUS: False, pygame.K_PERIOD: False, pygame.K_SLASH: False,
    pygame.K_0: False, pygame.K_1: False, pygame.K_2: False, pygame.K_3: False,
    pygame.K_4: False, pygame.K_5: False, pygame.K_6: False, pygame.K_7: False,
    pygame.K_8: False, pygame.K_9: False, pygame.K_COLON: False, pygame.K_SEMICOLON: False,
    pygame.K_LESS: False, pygame.K_EQUALS: False, pygame.K_GREATER: False, pygame.K_QUESTION: False,
    pygame.K_AT: False, pygame.K_a: False, pygame.K_b: False, pygame.K_c: False,
    pygame.K_d: False, pygame.K_e: False, pygame.K_f: False, pygame.K_g: False,
    pygame.K_h: False, pygame.K_i: False, pygame.K_j: False, pygame.K_k: False,
    pygame.K_l: False, pygame.K_m: False, pygame.K_n: False, pygame.K_o: False,
    pygame.K_p: False, pygame.K_q: False, pygame.K_r: False, pygame.K_s: False,
    pygame.K_t: False, pygame.K_u: False, pygame.K_v: False, pygame.K_w: False,
    pygame.K_x: False, pygame.K_y: False, pygame.K_z: False, pygame.K_LEFTBRACKET: False,
    pygame.K_BACKSLASH: False, pygame.K_RIGHTBRACKET: False, pygame.K_CARET: False, pygame.K_UNDERSCORE: False,
    pygame.K_BACKQUOTE: False, pygame.K_a: False, pygame.K_b: False, pygame.K_c: False,
    pygame.K_d: False, pygame.K_e: False, pygame.K_f: False, pygame.K_g: False,
    pygame.K_h: False, pygame.K_i: False, pygame.K_j: False, pygame.K_k: False,
    pygame.K_l: False, pygame.K_m: False, pygame.K_n: False, pygame.K_o: False,
    pygame.K_p: False, pygame.K_q: False, pygame.K_r: False, pygame.K_s: False,
    pygame.K_t: False, pygame.K_u: False, pygame.K_v: False, pygame.K_w: False,
    pygame.K_x: False, pygame.K_y: False, pygame.K_z: False, pygame.K_LEFTBRACKET: False,
    pygame.K_BACKSLASH: False, pygame.K_RIGHTBRACKET: False, pygame.K_CARET: False,
    pygame.K_LALT: False, pygame.K_RALT: False, pygame.K_BACKSPACE: False,
    pygame.K_CAPSLOCK: False, pygame.K_LCTRL: False, pygame.K_RCTRL: False,
    pygame.K_DELETE: False, pygame.K_DOWN: False, pygame.K_END: False,
    pygame.K_RETURN: False, pygame.K_ESCAPE: False, pygame.K_F1: False, pygame.K_F2: False,
    pygame.K_F3: False, pygame.K_F4: False, pygame.K_F5: False, pygame.K_F6: False,
    pygame.K_F7: False, pygame.K_F8: False, pygame.K_F9: False, pygame.K_F10: False,
    pygame.K_F11: False, pygame.K_F12: False, pygame.K_F13: False, pygame.K_F14: False,
    pygame.K_F15: False, pygame.K_HOME: False, pygame.K_INSERT: False,
    pygame.K_LEFT: False, pygame.K_NUMLOCK: False, pygame.K_PAGEDOWN: False,
    pygame.K_PAGEUP: False, pygame.K_PAUSE: False, pygame.K_PRINT: False, pygame.K_RIGHT: False,
    pygame.K_SCROLLLOCK: False, pygame.K_LSHIFT: False, pygame.K_RSHIFT: False,
    pygame.K_SPACE: False, pygame.K_TAB: False, pygame.K_UP: False,
    pygame.K_LEFT: False, pygame.K_RIGHT: False,
    # # Mouse buttons
    # pygame.MOUSEBUTTONDOWN: False,
    # pygame.MOUSEBUTTONUP: False,
    #pygame.MOUSEMOTION: False
}