import ast

def verifyExpression(expression):
    """
    #Generated by ChatGPT\n
    Verifies that the given expression does not contain any function calls.
    :param expression: The string expression to check.
    :return: True if no function calls are present, False otherwise.
    """
    try:
        # Parse the string into an abstract syntax tree
        tree = ast.parse(expression, mode='eval')

        # Walk through the AST nodes
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):  # Check for function calls
                return False

        return True
    except Exception as e:
        return False